
- name: play1
  hosts: webservers
  gather_facts : true
  tasks:
    - name: loop
      apt:
        name: "{{ item.package_name }}"
        state: "{{ item.package_state }}"
      loop:
        - { package_name: nginx, package_state: present}
        - { package_name: vim, package_state: present}
        - { package_name: curl, package_state: absent}

    - name: play2
      ping:
          
